name: interchange-examples-env
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
  - openeye
dependencies:
  # Core
  - python
  - pip
  - pydantic
  - openmm
  # OpenFF stack
  - openff-toolkit >=0.11.0
  # Optional features
  - unyt
  - mbuild
  - foyer >=0.11.3
  # Examples
  - nglview
  - ipywidgets >7,<8  # https://github.com/nglviewer/nglview/issues/1032
  - openeye-toolkits
  - pytest <7.0.0
  - nbval
  # Drivers
  - gromacs >=2021=nompi*
  - lammps >=2021
  - panedr
