name: full_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
        openeye:
          - true
          - false
    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
      COV: --cov=openff/interchange --cov-report=xml --cov-config=setup.cfg --cov-append

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/test_env.yaml
        extra-specs: |
          python=${{ matrix.python-version }}
          mamba

    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Install package
      run: |
        python setup.py develop --no-deps

    - name: Environment Information
      run: |
        conda info
        conda list
        mamba repoquery whoneeds jax
        mamba repoquery whoneeds pymbar

    - name: License OpenEye
      if: ${{ matrix.openeye == true }}
      run: |
        echo "${SECRET_OE_LICENSE}" > ${OE_LICENSE}
        python -c "from openeye import oechem; assert oechem.OEChemIsLicensed()"
      env:
        SECRET_OE_LICENSE: ${{ secrets.OE_LICENSE }}

    - name: Run mypy
      run: |
        mypy --namespace-packages -p "openff.interchange"

    - name: Run all tests
      if: always()
      run: |
        python -m pytest -r fE -nauto --durations=10 $COV openff/interchange/ -m "slow or not slow"

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
