name: minimal_tests

on:
  push:
    branches:
      - main
      - v0.3.0-staging
  pull_request:
    branches:
      - main
      - v0.3.0-staging

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    env:
      COV: --cov=openff/interchange --cov-report=xml --cov-config=setup.cfg --cov-append

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/minimal_env.yaml
        extra-specs: |
          python=${{ matrix.python-version }}

    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Install package
      run: |
        python -m pip install .
        python -m pip install -e ./plugins/

    - name: Environment Information
      run: |
        conda info
        conda list

    - name: Run unit tests
      if: always()
      run: |
        python -m pytest -v -nauto --durations=10 $COV openff/interchange/tests/unit_tests/
