name: minimal_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
    env:
      CI_OS: ${{ matrix.os }}
      PYVER: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/minimal_env.yaml
        extra-specs: |
          python=${{ matrix.python-version }}

    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Install package
      run: |
        python setup.py develop --no-deps

    - name: Environment Information
      run: |
        conda info
        conda list

    - name: Run unit tests
      if: always()
      run: |
        python -m pytest -v -nauto --durations=10 openff/interchange/tests/unit_tests/
